services:
  catalogue:
    build:
      dockerfile: catalogue.Dockerfile
    image: anil/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build:
      dockerfile: user.Dockerfile
    image: anil/user:1.0.0
    container_name: user
    depends_on:
    - redis
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    image: anil/frontend:1.0.0
    container_name: front 
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
  mongodb:
    build:
      dockerfile: mongodb.Dockerfile # it moves to mongodb directory
    image: anil/mongodb:1.0.0 # docker build -t --network roboshop --name mongodb  anil/mongodb:1.0.0
    container_name: mongo 
  redis:
    image: redis:7.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true you need to create network manually 