services:
  catalogue:
    build: ./CATALOGUE
    image: anill146/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./user
    image: anill146/user:1.0.0
    container_name: user
    depends_on:
    - redis
  cart:
    build: ./cart
    image: anill146/cart:1.0.0
  shipping:
    build: ./shipping
    image: anill146/shipping:1.0.0 
  frontend:
    build: ./frontend
    image: anill146/frontend:1.0.0
    container_name: front 
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart 
  mongodb:
    build: ./MONGODB # it moves to mongodb directory
    image: anill146/mongodb:1.0.0 # docker build -t --network roboshop --name mongodb  anil/mongodb:1.0.0
    container_name: mongo 
  redis:
    image: redis:7.0
    container_name: redis
  mysql:
    build: ./mysql
    image: anill146/mysql:1.0.0
    container_name: mysql

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true you need to create network manually 