services:
  catalogue:
    build:
      dockerfile: catalogue.Dockerfile
    image: anil/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    build:
      dockerfile: mongodb.Dockerfile # it moves to mongodb directory
    image: anil/mongodb:1.0.0 # docker build -t --network roboshop --name mongodb  anil/mongodb:1.0.0
    container_name: mongo 

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true you need to create network manually 